// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXRKGHkz0ovv3y_6R77wcC3FjxjfyGdI',
    appId: '1:596932026541:web:0aac09d6189bec39c0e624',
    messagingSenderId: '596932026541',
    projectId: 'spotify-d6824',
    authDomain: 'spotify-d6824.firebaseapp.com',
    storageBucket: 'spotify-d6824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1ENHMOJFLF5OYB-lXR3aHb6EVGxMrKk',
    appId: '1:596932026541:android:922a164e032313dac0e624',
    messagingSenderId: '596932026541',
    projectId: 'spotify-d6824',
    storageBucket: 'spotify-d6824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfB1p3uGLpJel45yaWAQk80Ym6ua8VnCk',
    appId: '1:596932026541:ios:48eeb13a27ca809fc0e624',
    messagingSenderId: '596932026541',
    projectId: 'spotify-d6824',
    storageBucket: 'spotify-d6824.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXRKGHkz0ovv3y_6R77wcC3FjxjfyGdI',
    appId: '1:596932026541:web:aac84c368cae6edfc0e624',
    messagingSenderId: '596932026541',
    projectId: 'spotify-d6824',
    authDomain: 'spotify-d6824.firebaseapp.com',
    storageBucket: 'spotify-d6824.firebasestorage.app',
  );
}
